<package format="3">
  <name>bbox_calculation</name>
  <version>0.0.1</version>
  <description>Bounding Box Calculation</description>
  <maintainer email="zhangji@cmu.edu">Ji Zhang</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>pcl_ros</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>message_filters</depend>

  <exec_depend>vehicle_simulator</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
